# Generated by Django 5.2.6 on 2026-06-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoiceline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
