# Generated by Django 5.2.6 on 2026-06-25 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dui', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='DUI')),
                ('firstName', models.CharField(max_length=255, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=255, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
