# Generated by Django 5.2.6 on 2026-06-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dui',
            field=models.CharField(blank=True, default='00000000-0', max_length=10, null=True, unique=True, verbose_name='DUI'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='cliente@example.com', max_length=254, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(blank=True, default='0000-0000', max_length=20, null=True, verbose_name='Número de teléfono'),
        ),
    ]
