# Generated by Django 5.2.6 on 2026-06-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_edited_at_alter_customer_dui_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dui',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='DUI'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
    ]
