# Generated by Django 5.2.6 on 2026-09-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_populate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
